function J_plane_func = J_plane_func(P1,P2,P3,rx,ry,rz,tx,ty,tz)
%J_plane_func
%    J_plane_func = J_plane_func(P1,P2,P3,RX,RY,RZ,TX,TY,TZ)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024-01-23 14:10:06

t2 = rx.^2;
t3 = ry.^2;
t4 = rz.^2;
t5 = t2+t3+t4;
t6 = 1.0./t5;
t7 = sqrt(t5);
t8 = 1.0./t7;
t9 = cos(t7);
t10 = sin(t7);
t11 = t9-1.0;
t12 = rx.*t8.*t10;
t13 = ry.*t8.*t10;
t14 = rz.*t8.*t10;
t15 = rx.*ry.*t6.*t11;
t16 = rx.*rz.*t6.*t11;
t17 = ry.*rz.*t6.*t11;
J_plane_func = [tx+P3.*(t13-t16)+P1.*(t6.*t11.*(t3+t4)+1.0)-P2.*(t14+t15),ty+P1.*(t14-t15)+P2.*(t6.*t11.*(t2+t4)+1.0)-P3.*(t12+t17),tz+P2.*(t12-t17)+P3.*(t6.*t11.*(t2+t3)+1.0)-P1.*(t13+t16),1.0];
end
