function J_plane_func = reg_J_plane_func(nx,ny,nz)
%reg_J_plane_func
%    J_plane_func = reg_J_plane_func(NX,NY,NZ)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024-01-21 16:37:44

t2 = nx.^2;
t3 = ny.^2;
t4 = nz.^2;
t5 = t2+t3+t4;
t6 = 1.0./sqrt(t5);
J_plane_func = [nx.*t6,ny.*t6,nz.*t6];
end
