function error = reg_error_func(nx,ny,nz)
%REG_ERROR_FUNC
%    ERROR = REG_ERROR_FUNC(NX,NY,NZ)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024-01-21 16:37:44

error = sqrt(nx.^2+ny.^2+nz.^2)-1.0;
end
